
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  database: deco_development
  username: 'angel'
  password: 'fr33l@nC3'
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: deco_test

production:
  <<: *default
  database: deco_production
  username:
  password:
